Repository cryptic-game/java-backend, pull requests merged in 2020-08, with the labels that each got.

#158 Added API Token Support
  java-base/src/main/java/net/cryptic_game/backend/base/BaseConfig.java
  java-base/src/main/java/net/cryptic_game/backend/base/api/netty/rest/RestApiLocation.java
  java-base/src/main/java/net/cryptic_game/backend/base/api/netty/rest/RestApiLocationProvider.java
  java-base/src/main/java/net/cryptic_game/backend/base/utils/HttpClientUtils.java
  java-daemon/src/main/java/net/cryptic_game/backend/daemon/App.java
  server/src/main/java/net/cryptic_game/backend/server/App.java
  server/src/main/java/net/cryptic_game/backend/server/daemon/DaemonHandler.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/WebSocketDaemonEndpoints.java
Labels: enhancement, security

#159 Add Chat Endpoints
  java-base/src/main/java/net/cryptic_game/backend/base/utils/DaemonUtils.java
  java-daemon-endpoints/src/main/java/net/cryptic_game/backend/endpoints/chat/ChatChannelEndpoints.java
  java-daemon-endpoints/src/main/java/net/cryptic_game/backend/endpoints/chat/ChatMessageEndpoint.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatAction.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatChannel.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatChannelAccess.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatMessage.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/User.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/WebSocketUserEndpoints.java
Labels: enhancement

#164 Improve hibernate sessions management
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiExecutor.java
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiParameterSpecialType.java
  java-base/src/main/java/net/cryptic_game/backend/base/sql/models/TableModel.java
  java-base/src/main/java/net/cryptic_game/backend/base/sql/models/TableModelAutoId.java
  java-daemon-endpoints/src/main/java/net/cryptic_game/backend/endpoints/UserSettingsEndpoints.java
  java-daemon-endpoints/src/main/java/net/cryptic_game/backend/endpoints/chat/ChatChannelEndpoints.java
  java-daemon-endpoints/src/main/java/net/cryptic_game/backend/endpoints/chat/ChatMessageEndpoint.java
  java-daemon-endpoints/src/main/java/net/cryptic_game/backend/endpoints/network/NetworkEndpoints.java
  java-daemon-endpoints/src/main/java/net/cryptic_game/backend/endpoints/network/NetworkInvitationEndpoints.java
  java-daemon-endpoints/src/main/java/net/cryptic_game/backend/endpoints/network/NetworkMemberEndpoints.java
  java-daemon-endpoints/src/main/java/net/cryptic_game/backend/endpoints/network/NetworkOwnerEndpoints.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatChannel.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatChannelAccess.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatMessage.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/Device.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceAccess.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceFile.java
  java-data/src/main/java/net/cryptic_game/backend/data/network/Network.java
  java-data/src/main/java/net/cryptic_game/backend/data/network/NetworkInvitation.java
  java-data/src/main/java/net/cryptic_game/backend/data/network/NetworkMember.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/Session.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/User.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/UserSetting.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/WebSocketUserEndpoints.java
Labels: enhancement, internal
