Repository cryptic-game/java-backend, pull requests merged in 2020-04, with the labels that each got.

#40 feature/33-add-chat-data-classes
  java-base/src/main/java/net/cryptic_game/backend/base/sql/models/TableModel.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/Channel.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChannelAccess.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatAction.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/Message.java
  server/src/main/java/net/cryptic_game/backend/server/App.java
  server/src/main/java/net/cryptic_game/backend/server/client/Client.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/WebSocketUserEndpoints.java
Labels: feature request

#45 Added name length check
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/WebSocketUserEndpoints.java
Labels: bug, enedpoint, security

#47 Added disconnecting daemon handling
  java-base/src/main/java/net/cryptic_game/backend/base/api/client/ApiClientList.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/Message.java
  server/src/main/java/net/cryptic_game/backend/server/daemon/DaemonHandler.java
  server/src/main/java/net/cryptic_game/backend/server/server/daemon/DaemonServerCodec.java
Labels: bug

#51 Added error message if the give uuid is not valid
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiEndpointExecutor.java
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiEndpointValidator.java
Labels: bug

#57 Added deletion of expired sessions on user login
  java-data/src/main/java/net/cryptic_game/backend/data/network/Network.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/Session.java
  server/src/main/java/net/cryptic_game/backend/server/App.java
  server/src/main/java/net/cryptic_game/backend/server/client/Client.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/WebSocketUserEndpoints.java
Labels: enhancement

#58 Added new Json system
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiEndpointCollection.java
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiEndpointExecutor.java
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiEndpointValidator.java
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiResponse.java
  java-base/src/main/java/net/cryptic_game/backend/base/api/netty/JsonApiServerContentHandler.java
  java-base/src/main/java/net/cryptic_game/backend/base/json/JsonBuilder.java
  java-base/src/main/java/net/cryptic_game/backend/base/json/JsonExclusionStrategy.java
  java-base/src/main/java/net/cryptic_game/backend/base/json/JsonSerializable.java
  java-base/src/main/java/net/cryptic_game/backend/base/json/JsonSerializableSerializer.java
  java-base/src/main/java/net/cryptic_game/backend/base/json/JsonTransient.java
  java-base/src/main/java/net/cryptic_game/backend/base/json/JsonTypeMappingException.java
  java-base/src/main/java/net/cryptic_game/backend/base/json/JsonUtils.java
  java-base/src/main/java/net/cryptic_game/backend/base/json/types/InstantTypeAdapter.java
  java-base/src/main/java/net/cryptic_game/backend/base/json/types/ZonedDateTimeAdapter.java
  java-base/src/main/java/net/cryptic_game/backend/base/utils/JsonBuilder.java
  java-base/src/main/java/net/cryptic_game/backend/base/utils/JsonSocketUtils.java
  java-base/src/main/java/net/cryptic_game/backend/base/utils/JsonUtils.java
Labels: enhancement, internal

#60 Added deletion of sessions on user deletion
  java-base/src/main/java/net/cryptic_game/backend/base/api/client/ApiClient.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/Session.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/User.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/WebSocketInfoEndpoints.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/WebSocketUserEndpoints.java
Labels: endpoint, enhancement
