Repository cryptic-game/java-backend, pull requests merged in 2020-05, with the labels that each got.

#74 Added H2 In-Memory Database for testing purposes
  .gitignore
  java-base/build.gradle.kts
  java-base/src/main/java/net/cryptic_game/backend/base/AppBootstrap.java
  java-base/src/main/java/net/cryptic_game/backend/base/BaseConfig.java
  java-base/src/main/java/net/cryptic_game/backend/base/config/ConfigUtils.java
  java-base/src/main/java/net/cryptic_game/backend/base/sql/SQLConnection.java
  java-base/src/main/java/net/cryptic_game/backend/base/sql/SQLServer.java
  java-base/src/main/java/net/cryptic_game/backend/base/sql/SQLServerType.java
Labels: enhancement, internal

#78 Use new JsonBuilder
  java-base/src/main/java/net/cryptic_game/backend/base/api/notification/NotificationEndpointCollection.java
  java-base/src/main/java/net/cryptic_game/backend/base/daemon/Daemon.java
  java-base/src/main/java/net/cryptic_game/backend/base/daemon/DaemonRegisterPacket.java
  java-base/src/main/java/net/cryptic_game/backend/base/daemon/Function.java
  java-base/src/main/java/net/cryptic_game/backend/base/daemon/FunctionArgument.java
  java-base/src/main/java/net/cryptic_game/backend/base/json/JsonBuilder.java
  java-base/src/main/java/net/cryptic_game/backend/base/utils/ApiUtils.java
  java-data/src/main/java/net/cryptic_game/backend/data/Inventory.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatChannel.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatChannelAccess.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatMessage.java
  java-data/src/main/java/net/cryptic_game/backend/data/currency/CurrencyAccess.java
  java-data/src/main/java/net/cryptic_game/backend/data/currency/CurrencyTransaction.java
  java-data/src/main/java/net/cryptic_game/backend/data/currency/CurrencyWallet.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/Device.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceAccess.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceFile.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceHardware.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceHardwareElement.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceServiceReq.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceWorkload.java
  java-data/src/main/java/net/cryptic_game/backend/data/network/Network.java
  java-data/src/main/java/net/cryptic_game/backend/data/network/NetworkInvitation.java
  java-data/src/main/java/net/cryptic_game/backend/data/network/NetworkMember.java
  java-data/src/main/java/net/cryptic_game/backend/data/service/Service.java
  java-data/src/main/java/net/cryptic_game/backend/data/service/ServiceBruteforce.java
  java-data/src/main/java/net/cryptic_game/backend/data/service/ServiceMiner.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/Session.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/UserSettings.java
  renovate.json
  server/src/main/java/net/cryptic_game/backend/server/server/daemon/DaemonServerCodec.java
  server/src/main/java/net/cryptic_game/backend/server/server/http/endpoints/HttpInfoEndpoint.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/WebSocketDaemonEndpoints.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/WebSocketInfoEndpoints.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/WebSocketUserEndpoints.java
Labels: enhancement, internal

#79 Issue/77 add websocket client
  java-base/build.gradle.kts
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/WebSocketPingPongHandler.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/WebSocketServerCodecInitializer.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/playground/PlaygroundContentHandler.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/playground/PlaygroundUtils.java
  server/www/3rdpartylicenses.txt
  server/www/CNAME
  server/www/LICENSE
  server/www/assets/icons/icon-128x128.png
  server/www/assets/icons/icon-144x144.png
  server/www/assets/icons/icon-152x152.png
  server/www/assets/icons/icon-192x192.png
  server/www/assets/icons/icon-384x384.png
  server/www/assets/icons/icon-512x512.png
  server/www/assets/icons/icon-72x72.png
  server/www/assets/icons/icon-96x96.png
  server/www/assets/icons/icon.svg
  server/www/favicon.ico
  server/www/index.html
  server/www/main-es2015.c07b43db906a5c7a5ec1.js
  server/www/main-es5.c07b43db906a5c7a5ec1.js
  server/www/polyfills-es2015.a2c1af2b1be41024173b.js
  server/www/polyfills-es5.85d83c3040e41a367f6b.js
  server/www/runtime-es2015.f8b979f66300b1e53384.js
  server/www/runtime-es5.f8b979f66300b1e53384.js
  server/www/styles.3b1a0cc0718010d64ea4.css
Labels: enhancement

#82 Added user/get endpoint #52
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/WebSocketUserEndpoints.java
Labels: endpoint, enhancement

#84 Fixed high priority security vulnerability with the Json system
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiResponseType.java
  java-base/src/main/java/net/cryptic_game/backend/base/api/notification/ApiNotification.java
  java-base/src/main/java/net/cryptic_game/backend/base/daemon/Daemon.java
  java-base/src/main/java/net/cryptic_game/backend/base/daemon/DaemonRegisterPacket.java
  java-base/src/main/java/net/cryptic_game/backend/base/daemon/Function.java
  java-base/src/main/java/net/cryptic_game/backend/base/daemon/FunctionArgument.java
  java-base/src/main/java/net/cryptic_game/backend/base/interfaces/JsonSerializable.java
  java-base/src/main/java/net/cryptic_game/backend/base/interfaces/ResponseType.java
  java-base/src/main/java/net/cryptic_game/backend/base/sql/models/TableModel.java
  java-base/src/main/java/net/cryptic_game/backend/base/utils/JsonBuilder.java
  java-base/src/main/java/net/cryptic_game/backend/base/utils/JsonUtils.java
  java-data/src/main/java/net/cryptic_game/backend/data/Inventory.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatChannel.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatChannelAccess.java
  java-data/src/main/java/net/cryptic_game/backend/data/chat/ChatMessage.java
  java-data/src/main/java/net/cryptic_game/backend/data/currency/CurrencyAccess.java
  java-data/src/main/java/net/cryptic_game/backend/data/currency/CurrencyTransaction.java
  java-data/src/main/java/net/cryptic_game/backend/data/currency/CurrencyWallet.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/Device.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceAccess.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceFile.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceHardware.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceHardwareElement.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceServiceReq.java
  java-data/src/main/java/net/cryptic_game/backend/data/device/DeviceWorkload.java
  java-data/src/main/java/net/cryptic_game/backend/data/network/Network.java
  java-data/src/main/java/net/cryptic_game/backend/data/network/NetworkInvitation.java
  java-data/src/main/java/net/cryptic_game/backend/data/network/NetworkMember.java
  java-data/src/main/java/net/cryptic_game/backend/data/service/Service.java
  java-data/src/main/java/net/cryptic_game/backend/data/service/ServiceBruteforce.java
  java-data/src/main/java/net/cryptic_game/backend/data/service/ServiceMiner.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/Session.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/User.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/UserSettings.java
  server/src/main/java/net/cryptic_game/backend/server/client/Client.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/WebSocketUserEndpoints.java
Labels: bug, high priority, internal, security

#95 Renamed all `name` to `username`
  java-data/src/main/java/net/cryptic_game/backend/data/user/User.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/WebSocketUserEndpoints.java
Labels: bug

#101 Added UserSettingsEndpoints
  java-daemon-endpoints/src/main/java/net/cryptic_game/backend/endpoints/UserSettingsEndpoints.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/UserSetting.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/UserSettings.java
Labels: endpoint, enhancement

#102 Add Api Test Editor
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiEndpointData.java
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiEndpointList.java
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiExecutor.java
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiParser.java
  java-base/src/main/java/net/cryptic_game/backend/base/config/ConfigUtils.java
  java-daemon-endpoints/src/main/java/net/cryptic_game/backend/endpoints/TestEndpoints.java
  java-daemon/src/main/java/net/cryptic_game/backend/daemon/api/DaemonEndpointHandler.java
  server/src/main/java/net/cryptic_game/backend/server/App.java
  server/src/main/java/net/cryptic_game/backend/server/ServerConfig.java
  server/src/main/java/net/cryptic_game/backend/server/server/daemon/DaemonEndpointHandler.java
  server/src/main/java/net/cryptic_game/backend/server/server/http/HttpEndpointHandler.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/WebSocketEndpointHandler.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/WebSocketServerCodec.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/WebSocketServerCodecInitializer.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/WebSocketUserEndpoints.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/playground/PlaygroundContentHandler.java
  server/www/config.json
  server/www/index.html
  server/www/main-es2015.2b862fc895995be8351c.js
  server/www/main-es2015.ec73cb36000ac825863c.js
  server/www/main-es5.2b862fc895995be8351c.js
  server/www/main-es5.ec73cb36000ac825863c.js
Labels: endpoint, enhancement

#104 Removed mail address
  java-base/build.gradle.kts
  java-base/src/main/java/net/cryptic_game/backend/base/utils/ValidationUtils.java
  java-data/src/main/java/net/cryptic_game/backend/data/user/User.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/WebSocketUserEndpoints.java
Labels: enhancement
