Repository cryptic-game/java-backend, pull requests merged in 2020-03, with the labels that each got.

#14 Updated Gradle to 6.2.2. (#13)
  gradle/wrapper/gradle-wrapper.properties
Labels: internal

#15 Issue/12 Switch to Kotlin DSL
  .gitignore
  build.gradle
  build.gradle.kts
  java-base/build.gradle
  java-base/build.gradle.kts
  java-daemon/build.gradle
  java-daemon/build.gradle.kts
  java-data/build.gradle
  java-data/build.gradle.kts
  java-data/src/test/java/.gitkeep
  java-data/src/test/resources/.gitkeep
  server/build.gradle
  server/build.gradle.kts
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/WebSocketLogger.java
  settings.gradle
  settings.gradle.kts
Labels: internal

#21 Remove Encryption from Session
  java-data/src/main/java/net/cryptic_game/backend/data/user/Session.java
  server/src/main/java/net/cryptic_game/backend/server/server/websocket/endpoints/UserEndpoints.java
Labels: enhancement

#30 Add Error Message if Provided JSON is Invalid
  java-base/src/main/java/net/cryptic_game/backend/base/api/netty/JsonApiServerContentHandler.java
  java-base/src/main/java/net/cryptic_game/backend/base/netty/NettyChannelHandler.java
Labels: bug

#34 Added Support for Dates in the Api
  java-base/src/main/java/net/cryptic_game/backend/base/api/endpoint/ApiEndpointValidator.java
Labels: feature request
